apiVersion: v1
kind: Service
metadata:
  name: zipnews-api-svc
  labels:
    app: zipnews-api
spec:
  ports:
    - name: zipnews-api
      protocol: "TCP"
      port: 5000
      targetPort: 5000
  selector:
    app: zipnews-api
  type: NodePort